### ISSUE TITLE
unexpected '$password' (T_VARIABLE) in /storage/ssd3/.........

### ISSUE THREAD

**Issue by sizar3x** [SheehabX/FB-Phishing#1]
bro I just use you use you script and host them in 000webhost and when enter the email and password this error comes up

**Comment by SheehabX** [comment]
Whats the error?

**Comment by shezylou** [comment]
Parse error: syntax error, unexpected ';' in C:\xampp\htdocs\fbsecurity\do_action.php on line 3

**Comment by socialAPIS** [comment]
You have missing ';' somewhere.
Ive build an phishing who can check if you habe put the right Password

**Comment by SheehabX** [comment]
Fixed
